### ISSUE TITLE
怎么清除图片？

### ISSUE THREAD

**Issue by yuhaizr** [plpcm/lua-resty-checkcode#1]
这么没有包含清除，过期的图片的功能吗？需要在写个脚本来清理图片？

**Comment by plpcm** [comment]
由于图片占用空间很小，而且每次重复图片会重新生成，所以没考虑删除机制，如果觉得仍然不能接收可以定期删除。

**Comment by yuhaizr** [comment]
> 于图片占用空间很小，而且每次重复图片会重新生成，所以没考虑删除机制，如果觉得仍然不能接收可以定期删除。

可以定期删除，问题不大
